### ISSUE TITLE
Update for cstruct 2.0

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-pcap#16]
See ocaml/opam-repository#6405.

**Comment by dsheets** [comment]
I'm not sure what the failed configuration was and I can't reproduce the issue. @hannesm reports that it works for him and it now works for me in several different configurations. I've filed ocaml/opam-repository#6546 to revert the previous constraint. Sorry for the noise.

**Comment by hannesm** [comment]
some investigation shows that the `mirage` dependent code in this repository should either be updated or removed... it uses lwt.syntax without claiming so... maybe you had mirage installed + somehow enabled?

**Comment by dsheets** [comment]
The Mirage-specific libraries in use are:

```
mirage-block-unix.2.2.0
mirage-block.0.2
mirage-clock-unix.1.0.0
mirage-console.2.1.3
mirage-flow.1.1.0
mirage-net-unix.2.2.2
mirage-profile.0.7.0
mirage-tc.0.3.0
mirage-unix.2.5.0
```

but the error occurred with potentially different versions of these libraries. These libraries at these versions don't appear to have issues with `pcap-format.0.4.0` + `cstruct.2.0.0`. It very well could have been that I misread `protocol-9p` as `pcap-format` or something similarly stupid/hasty.

**Comment by hannesm** [comment]
ah, and gladly in the `opam`file here, `--enable-mirage` (for `_oasis`) is never done... thus the code in the `mirage/` subdirectory here is never compiled...
