### ISSUE TITLE
Compile error on https://github.com/mor1/ocaml-pcap/tree/refactor

### ISSUE THREAD

**Issue by infidel** [mirage/ocaml-pcap#2]
As requested, I tried building the in-progress branch and I get this error:

> - /home/luked/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I lib/ps -I lib -package cmdliner -package cstruct -syntax camlp4o -package cstruct.syntax -package ipaddr -package lwt -package lwt.unix -I unix -I lib -o unix/commands.cmo unix/commands.ml
>   File "unix/commands.ml", line 98, characters 25-34:
>   Error: This expression has type int32 but an expression was expected of type
>        int
>   Command exited with code 2.

Using Int32.add instead of (+) fixed it, so I'm guessing this is something specific to OCaml 4.01.0 ?

**Comment by yomimono** [comment]
This was merged back in https://github.com/mirage/ocaml-pcap/pull/3 and is now tested by CI.  Very belated thanks for the report, @infidel !
