### ISSUE TITLE
regression: little and big-endian detection

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-pcap#9]
since #3 was merged (no release since then), the API changed... specifically, there is no longer the magic to detect whether the pcap was little or big endian (`Pcap.detect`, see https://github.com/yomimono/mirage-net-pcap/blob/e0ee0dc135cbd3b3e70e3e0e12116e87d25e1a95/lib/netif.ml#L89 , also in `lib_test` here).

I think that functionality was pretty nice and should be restored before a release... @mor1 ?

**Comment by mor1** [comment]
Agree. I was confused about what my intent I think...

**Comment by mor1** [comment]
This specific issue resolved in #11

**Comment by hannesm** [comment]
@mor1 cool, did you write a regression test? :)

**Comment by hannesm** [comment]
this is fixed (and 0.4.0 contains a detect function)
